# Generated by Django 5.0.2 on 2024-06-08 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField(blank=True)),
                ('rephrased_text', models.TextField(blank=True)),
                ('audio', models.FileField(blank=True, upload_to='audio/')),
            ],
        ),
    ]
