# Generated by Django 5.0.2 on 2024-06-08 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accessibility', '0002_alter_comment_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='accessibility.location'),
        ),
    ]
